local map = require("configs.utils").map
map("n", "<leader><space>", function()
  return require("telescope.builtin").live_grep()
end)
map("n", "<leader>f", function()
  return require("telescope.builtin").find_files()
end)
map("n", "<leader>b", function()
  return require("telescope.builtin").buffers()
end)
