#!/usr/bin/env zsh
local fek() { echo "usage: cd into path of nix store derivation given by executable" >&2; }
[[ $# == 1 ]] || { fek && return 1; }
(( $+commands[$1] )) || { fek && return 1; }
dir="${commands[$1]:P:h}"
[[ "${dir:t}" == bin ]] && dir="${dir:h}"
[[ -d "$dir" ]] || { fek && return 1; }
cd -- "$dir"
