#!/usr/bin/env zsh

command -v gpg >/dev/null 2>&1 || { echo "need gpg installed" >/dev/stderr; return 1; }
command -v curl >/dev/null 2>&1 || { echo "need curl installed" >/dev/stderr; return 1; }

URL=$(
  gpg --passphrase -c -a |
    curl -s -d "jscrypt=no" -d "lifetime=3600" \
      -d "shorturl=yes" --data-urlencode "paste@-" \
      https://defuse.ca/bin/add.php -D - |
    grep Location | cut -d " " -f 2 | tr -d '\r\n'
)
echo "wget $URL?raw=true -q -O - | gpg -d -q --passphrase"
