#!/usr/bin/env zsh

local IFS=$'\t\n'
local tempfile="$(mktemp)"
local ranger_cmd=(
  command
  ranger
  --cmd="map Q chain shell echo %d > "$tempfile"; quitall"
)

${ranger_cmd[@]} "$@"
if [[ -f "$tempfile" ]] && [[ "$(<"$tempfile")" != "$(echo -n "$(pwd)")" ]]; then
  cd -- "$(<"$tempfile")" || return
fi
command rm -f -- "$tempfile" 2>/dev/null
