#!/usr/bin/env zsh
echo "Rebuilding"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

if [ -f /etc/os-release ]; then
  sudo nixos-rebuild \
    --flake '/etc/nixos#'"$(hostname)" \
    ${1+"$@"} switch
else
  cd $HOME/src/personal/nixos-configs >/dev/null || exit
  if (( ${+commands[darwin-rebuild]} )) ; then
    darwin-rebuild --flake $HOME/src/personal/nixos-configs ${1+"$@"} switch
  else
      local nix() {
      command nix --extra-experimental-features 'nix-command flakes' $@
    }
    nix build .#darwinConfigurations."${"$(hostname)"%\.local}".system --keep-going ${1+"$@"}
    ./result/sw/bin/darwin-rebuild --flake $HOME/src/personal/nixos-configs ${1+"$@"} switch
  fi
  rm -f $HOME/src/personal/nixos-configs/result
fi
