#!/usr/bin/env zsh

set -x
rm -rf ~/.cache/{hererocks,luarocks,nvim}
rm -rf "$XDG_CACHE_HOME/nvim/"
rm -rf ~dots/dots/nvim/plugin/packer_compiled.lua
rm -rf ~/.local/share/nvim/site/pack
set +x

echo "run nvim -c 'lua require(\"plugins\")' to bootstrap vim"
