name: Build configuration

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: hazel-nix-configs
          authToken: "${{ secrets.CACHIXCI }}"
          extraPullNames: "nix-community,hercules-ci"
      - run: nix -Lv flake check
      - run: nix -Lv build ".#"darwinConfigurations.Hazels-MacBook-Pro.config.system.build.toplevel
      - run: nix -Lv develop -c echo OK
