name: Build configuration

on:
  push:
    branches: [main]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), 'flake.lock: Update')"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: hazel-nix-configs
          authToken: "${{ secrets.CACHIXCI }}"
          extraPullNames: "nix-community,hercules-ci"
      - run: nix -Lv flake check
      - run: nix -Lv build ".#"darwinConfigurations.x86_64-darwin.config.system.build.toplevel
      - run: nix -Lv develop -c echo OK
