name: Build configuration

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            path: >-
              .#darwinConfigurations.x86_64-darwin.config.system.build.toplevel
          # - os: ubuntu-latest
          #   path: >-
          #     .#packages.x86_64-linux.neovim
          #     .#nixosConfigurations.x86_64-linux.config.system.build.toplevel
    if: "! contains(toJSON(github.event.commits.*.message), 'flake.lock: Update')"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          paths: ${{ matrix.path }}
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
