name: Build configuration

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            path: darwinConfigurations.x86_64-darwin.config.system.build.toplevel
          - os: ubuntu-latest
            path: packages.x86_64-linux.neovim-bundled
    if: "! contains(toJSON(github.event.commits.*.message), 'flake.lock: Update')"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: hazel-nix-configs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: "nix-community,hercules-ci,pre-commit-hooks"
      - run: nix -Lv flake check
      - run: nix -Lv build ".#"${{ matrix.path }}
      - run: nix -Lv develop -c echo OK
