name: "Update"
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: hazel-nix-configs
          authToken: "${{ secrets.CACHIXCI }}"
          extraPullNames: "nix-community,hercules-ci"
      - name: update
        run: |
          set -xeuo pipefail
          git config --global user.email "hazel@theweaklys.com"
          git config --global user.name "Hazel Weakly"
          nix develop -c nix flake update --commit-lock-file
          nix -Lv flake check
          nix -Lv build ".#"darwinConfigurations.Hazels-MacBook-Pro.config.system.build.toplevel
          nix -Lv develop -c echo OK
      - run: |
          git push origin HEAD
