name: "Update"
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # flakes doesn't work on shallow clones
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: hazel-nix-configs
          authToken: "${{ secrets.CACHIXCI }}"
          extraPullNames: "srid,nrdxp,nix-community,iohk,hercules-ci,ghcide-nix,eigenvalue,all-hies"
      - name: update
        run: |
          set -xeuo pipefail
          git config --global user.email "hazel@theweaklys.com"
          git config --global user.name "Hazel Weakly"
          nix develop -c nix flake update --commit-lock-file
          nix -Lv flake check
          nix -Lv build ".#"nixosConfigurations.hazel{weakly,xps}.config.system.build.toplevel
          nix -Lv develop -c echo OK
      - run: |
          git commit -m "auto-update inputs [skip ci]"
          git push origin HEAD
