name: "Update"
on:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.MERCURY_NIXOS_CONFIGURATION }}
      - name: update
        run: |
          set -xeuo pipefail
          git config --global user.email "hazel@theweaklys.com"
          git config --global user.name "Hazel Weakly"
          nix develop -c nix flake update --commit-lock-file
      - uses: cachix/cachix-action@v10
        with:
          name: hazel-nix-configs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: "nix-community,hercules-ci,pre-commit-hooks"
      - run: nix -Lv build .#nixosConfigurations.x86_64-linux.config.system.build.toplevel
      - run: nix -Lv develop -c echo OK
      - run: git push origin HEAD
